config/routes.rb
Rails.application.routes.draw do
  resources :wishlists, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # resources :order_items, only: []
  resources :items, only: [:index, :show]
  resources :orders, only: [:index, :show, :destroy]
  resources :users, only: [:new, :create, :destroy, :edit, :update, :show]

  post "/add_order/:id", to: "order_items#add_or_create", as: "add_order"
  post "/add_wishlist/:id", to: "wishlist_items#add_to_wishlist", as: "add_wishlist"
  get "/", to: "static#greetings", as: "greetings"
  get "/goodbye", to: "static#goodbye", as: "bye"
  get "/about", to: "static#about"
  get "/contact", to: "static#contact"

  post "/purchase", to: "orders#purchase", as: "purchase"

  delete "/remove_item/:id", to: "order_items#remove_item", as: "remove_item"
  delete "/remove_item_wishlist/:id", to: "wishlist_items#remove_item", as: "remove_item_from_wishlist"
  
  get "/login", to: "users#login", as: "login"
  post "/login", to: "users#process_login"
  get "/logout", to: "users#logout", as: "logout"
  get "/user_deleted", to: "users#user_deleted", as: "user_deleted"
  
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    has_many :items, through: :order_items
    belongs_to :user

    def total_price
        sum = 0
        self.items.each do |item|
            sum += item.price
        end
        sum
    end

    def item_quantity
        hash = {}
        current_order = Order.find_by(status: "Pending")
        current_order.items.each do |item| 
            if hash[item.name] == nil
                hash[item.name] = 1
            else
                hash[item.name] += 1
            end
        end
        hash
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.where(user_id: session[:user_id])
    @current_order = Order.find_by(status: "Pending", user_id: session[:user_id])
  end

  def show
    @order = Order.find(params[:id])
  end

  def purchase
    @order = Order.find_by(status: "Pending", user_id: session[:user_id])
    @order.update(status: "Purchased") 
    redirect_to order_path(@order.id)
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  # def add_or_create
  #   ##customized create
  #   # byebug
  #   # @user = User.find(params[:id])
    
  # end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div>
<div class="my_orders">
    <h1 class="order_history"> Order History </h1>
    <ul class="order_history">
        <% @orders.each do |order| %>
            <%if order.status == "Purchased"%>
                <li class="form"> Order Number: <%= order.id %>
                    <div class="purchased"> Status: <%= order.status%> </div>
                    Total Order Price: <%= number_to_currency(order.total_price)%> 
                    <br>
                    <%= button_to "View Order", order_path(order.id), method: 'get', class: "btn btn-outline-success" %> 
                </li>
            <% end %>
        <%end %>
    </ul>
</div>
<% if @current_order %>
    <div class="my_order">
        <h1 class="current_order"> Current Order </h1>
        <div class="form", id="order">
            <div class="pending"> Status: <%= @current_order.status %> </div>
            <div class="order_number"> Order Number: <%= @current_order.id %> </div>
            <br>
            <div class="items_order"> 
                Items:
                <ul class= "item_hash">
                    <%@current_order.item_quantity.each do |item_name, count| %>
                        <li><%= item_name %> - Quantity: <%= count %> </li>
                    <%end%>
                </ul>
            </div>
            <div class="price"> Total: <%= number_to_currency(@current_order.total_price) %> </div>
            <%= button_to "View Order", order_path(@current_order.id), method: "get", class: "btn btn-outline-success", id: "view_pending_order"%>
        </div>
    </div>
<% end %>
</div>

app/views/orders/show.html.erb
<div class="form", id="order-form">

<h1> Order Number: <%= @order.id%> </h1>

<%if @order.status == "Purchased"%>
    <div class="purchased"> Status: <%= @order.status%> </div>
<%else%>
    <div class="pending", id="pending-order"> Status: <%= @order.status%> </div>
<%end%>

<ul class="order-ul">
    <% @order.items.each do |item| %>
        <li class="order-item-list"> Item: <%= link_to item.name, item_path(item.id) %> 
        Price: <%= number_to_currency(item.price) %> 
        <%if @order.status == "Pending"%>
            <%= button_to "Remove", remove_item_path(item.id), method: "delete", class: "btn btn-outline-danger btn-sm" %></li>
        <% end %>
    <%end%>

</ul>



<div> 
    Order Total: <%= number_to_currency(@order.total_price) %> 
    <%if @order.status == "Pending"%>      
    <br>
    <br>
        <%= button_to "Continue Shopping", items_path, method: "get", class: "btn btn-outline-success btn-sm" %>     
        <%= button_to "Complete Purchase", purchase_path, data: {:confirm => "Are you sure you want to complete your purchase?"}, class: "btn btn-outline-success btn-sm" %>
        <%= button_to "Delete Order", order_path(@order.id), method: "delete", data: {:confirm => "Are you sure you want to delete your order?"}, class: "btn btn-outline-danger btn-sm"%>
    <%end%>
</div>
 <br>
    <%= button_to "Back to Orders", orders_path, method: "get", class: "btn btn-outline-secondary btn-sm", id: "back-to-orders" %>

    </div>