config/routes.rb
Rails.application.routes.draw do
  resources :wishlists, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # resources :order_items, only: []
  resources :items, only: [:index, :show]
  resources :orders, only: [:index, :show, :destroy]
  resources :users, only: [:new, :create, :destroy, :edit, :update, :show]

  post "/add_order/:id", to: "order_items#add_or_create", as: "add_order"
  post "/add_wishlist/:id", to: "wishlist_items#add_to_wishlist", as: "add_wishlist"
  get "/", to: "static#greetings", as: "greetings"
  get "/goodbye", to: "static#goodbye", as: "bye"
  get "/about", to: "static#about"
  get "/contact", to: "static#contact"

  post "/purchase", to: "orders#purchase", as: "purchase"

  delete "/remove_item/:id", to: "order_items#remove_item", as: "remove_item"
  delete "/remove_item_wishlist/:id", to: "wishlist_items#remove_item", as: "remove_item_from_wishlist"
  
  get "/login", to: "users#login", as: "login"
  post "/login", to: "users#process_login"
  get "/logout", to: "users#logout", as: "logout"
  get "/user_deleted", to: "users#user_deleted", as: "user_deleted"
  
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :order_items
    has_many :orders, through: :order_items
    has_many :wishlist_items
    has_many :wishlists, through: :wishlist_items
    belongs_to :category

    def self.search(search, category) 
        if category != nil && category != ""
            category_items = Item.where(category_id: category)
            if search != "" && search != nil
                items = category_items.where("name LIKE '%#{search}%'")
            else 
                category_items
            end
        else 
            if search != "" && search != nil
                items = Item.where("name LIKE '%#{search}%'")
            else 
                Item.all 
            end
        end
        
    end

  

    # def self.all_categories
    #     Item.distinct.pluck(:category)
    # end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if params[:category] != nil && params[:category] != ""
      @one_category = true
      @categories = Category.where(id: params[:category])
      @items = Item.search(params[:search], @categories[0])
    else
      @one_category = false
      @categories = Category.all
      @items = Item.search(params[:search], params[:category])
    end

    if @items == []
      flash.now[:message] = "No items found. Please search again"
      @nothing_searched = true 
    else 
      @nothing_searched = false
    end
    render :index
  end

  def show 
    @item = Item.find(params[:id])
    if session[:user_id]
      @wishlists = Wishlist.where(user_id: session[:user_id])
    end
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<center>
<% if flash.now[:message] %>
  <div class="alert alert-primary"> 
    <%= flash.now[:message]%>
  </div>
<%end%>
</center>

<% if @nothing_searched == false %>
<h1> Products </h1>
  <ul <% if @one_category %>
            class="One_Category"
          <%else%>
            class="All_Categories"
          <%end%>>
      <% @categories.each do |category|%>
        <h3> <%= category.name.titleize %></h3>
          <% @items.each do |item|%>
            <%if item.category_id == category.id%>
              <li>
                <%= link_to item.name, item_path(item.id), class:"shop" %> 
                <%= button_to "Add To Order", add_order_path(item.id), method: "post", class:"btn btn-outline-success btn-sm"%>
              </li>
            <%end%>
        <%end%>
      <%end%>
  </ul>
<%end%>

app/views/items/show.html.erb
<div class="form", id="item-form">
    <h2> <%= @item.name %> </h2>

    <p> Price: <%= number_to_currency(@item.price) %> </p>
    <p> Description: <%= @item.description %> </p>
    <img src= <%= @item.image %>>
    <br>
    <%= button_to "Add to Order", add_order_path(@item.id), method: 'post', class:"btn btn-outline-success", id: "add-order-button" %>

    <%= form_tag(add_wishlist_path(@item.id), {:class => "wishlist-form"}) do %>
    <% if @wishlists != nil && @wishlists != [] %>
        <%= select_tag :wishlist, options_from_collection_for_select(@wishlists, "id", "name"), class: "form-control", id: "select-wishlist"%>
        <%= submit_tag ("Add to Wishlist"), class:"btn btn-outline-success", id: "add-wishlist-button"%>
    <% end %>
    
    <%end%>
</div>