config/routes.rb
Rails.application.routes.draw do
  resources :wishlists, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # resources :order_items, only: []
  resources :items, only: [:index, :show]
  resources :orders, only: [:index, :show, :destroy]
  resources :users, only: [:new, :create, :destroy, :edit, :update, :show]

  post "/add_order/:id", to: "order_items#add_or_create", as: "add_order"
  post "/add_wishlist/:id", to: "wishlist_items#add_to_wishlist", as: "add_wishlist"
  get "/", to: "static#greetings", as: "greetings"
  get "/goodbye", to: "static#goodbye", as: "bye"
  get "/about", to: "static#about"
  get "/contact", to: "static#contact"

  post "/purchase", to: "orders#purchase", as: "purchase"

  delete "/remove_item/:id", to: "order_items#remove_item", as: "remove_item"
  delete "/remove_item_wishlist/:id", to: "wishlist_items#remove_item", as: "remove_item_from_wishlist"
  
  get "/login", to: "users#login", as: "login"
  post "/login", to: "users#process_login"
  get "/logout", to: "users#logout", as: "logout"
  get "/user_deleted", to: "users#user_deleted", as: "user_deleted"
  
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user, optional: true
  has_many :wishlist_items
  has_many :items, through: :wishlist_items
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

  before_action :find_wishlist, only: [:show, :edit, :update, :destroy]

  def index
    @wishlists = Wishlist.where(user_id: session[:user_id])
  end

  def show
  end

  def new
    @wishlist = Wishlist.new
  end
  
  def create
    @wishlist = Wishlist.new(name: wishlist_params[:name], user_id: session[:user_id])
    if @wishlist.save
      redirect_to wishlist_path(@wishlist.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @wishlist.update(wishlist_params)
      redirect_to wishlist_path(@wishlist.id)
    else 
      render :edit
    end
  end

  def destroy
    @wishlist.destroy
    flash[:message] = "Your wishlist has been deleted"
    redirect_to wishlists_path
  end

  private

  def wishlist_params
    params.require(:wishlist).permit(:name)
  end

  def find_wishlist
    @wishlist = Wishlist.find(params[:id])
  end

end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_wishlist_form.html.erb
<% if @wishlist.errors %>
  <% @wishlist.errors.full_messages.each do |error| %>
    <div class="alert alert-danger">
      <center> <%= error %> </center>
    </div>
  <% end %>
<% end %>

<div class="form">
  <%= form_for @wishlist do |f| %>
    <%= f.label :name, "Create New List:" %>
    <%= f.text_field :name , class: 'form-control'%>
    <br>
    <%= f.submit button_text, class: "btn btn-outline-success"%>
  <% end %>
</div>

app/views/wishlists/edit.html.erb
<%= render partial: "wishlist_form", locals: {button_text: "Update Wishlist"} %>

app/views/wishlists/index.html.erb
<% if flash[:message] %>
 <center> 
    <div class="alert alert-primary"> 
        <%= flash[:message]%>
    </div> 
</center>
<%end%>
<div class="form">
    <h2> My Wishlists </h2>

    <% @wishlists.each do |wishlist|%>
    <br>
    <div><%= wishlist.name.titleize %>
        <br>
        <%= link_to "View", wishlist_path(wishlist.id) %>/ 
        <%= link_to "Edit", edit_wishlist_path(wishlist.id) %>/
        <%= link_to "Delete", wishlist_path(wishlist.id),
                            method: "delete",
                            data: {:confirm => "Are you sure you want to delete this wishlist?"} %>
    </div>

    <% end %>
    <br>
    <%= button_to "Create New Wishlist", new_wishlist_path, method: "get", class: "btn btn-outline-success"%>
</div>

app/views/wishlists/new.html.erb
<%= render partial: "wishlist_form", locals: {button_text: "Create Wishlist"} %>

app/views/wishlists/show.html.erb
<% if flash[:message] %>
 <center> 
    <div class="alert alert-danger"> 
        <%= flash[:message]%>
    </div> 
</center>
<%end%>

<div class="form", id="wishlist-form">
    <h2 class= "wishlist-title"><%= @wishlist.name.titleize %></h2>

    <ul class="wishlist-ul">
        <% @wishlist.items.each do |item| %>
            <li class="items-on-wishlist">
                <%= link_to item.name, item_path(item)%> 
                <%=button_to "Add to order", add_order_path(item.id), method: "post", class: "btn btn-outline-success btn-sm"%> 
                <%= button_to "Remove", remove_item_from_wishlist_path(@wishlist.id), method: "delete", params:{item: item.id}, class: "btn btn-outline-danger btn-sm"%> 
            </li>
        <% end %>
    </ul>

    <%= %>

    <%= button_to "Delete Wishlist", wishlist_path(@wishlist.id), method: "delete", 
                        data: {:confirm => "Are you sure you want to delete this list?"}, class: "btn btn-outline-secondary", id: "delete-wishlist"%>
</div>